---
title: "PSY317L Guides"
author: "James P. Curley & Tyler M. Milewski"
date: "June 28, 2020"
output: bookdown::gitbook
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This books is still in progress !!!   This is a draft.



# Welcome to PSY317! 
The following is a simple guide to R studio. 


What this guide contains....  That it's mainly a how to implement stuff in R, but it also touches on bits of stats and data theory where applicable



## What this book includes and what it doesn't

This is in between a textbook and a study guide. We're trying to build materials that will enable students to quickly find what they're looking for to help them understand these statistical concepts.

This book is primarily aimed at the content in PSY317L (and PSY1XXR), but occasionally we describe concepts that we don't directly cover in these courses.  This is when we feel that it's worth explaining things in a bit more detail for those students that want to know a bit more about a subject.


## How to use this guide

This guide covers the material presented in the video segments. In some parts, we go beyond what is presented. This is to supplement the material and to help you understand the content or to round out some subjects a little more. You will not be tested directly on information that is in this guide if it did not appear in the video segments. Quizzes and tests are only based on the videos. This guidebook is exactly that - an extra reference to help you understand that material and a place to look for help or answers.


## Acknowledgements

This guidebook is built upon the work of several others' teaching materials.  In particular, Danielle Navarro's book....  also some examples come from Andy Field's intro to statistics using R



## References

The following books are all freely avaiable online (like this one!) and are helpful resources

wilke - visualizing

wickham grolemund - intro R

other wickham books?

danielle navarro - intro stats






## Other places to find help about R

Rstudio - cheatsheets, community pages

???



## Other places to find help about R and Statistics

With statistics stuff, you can never really have enough resources. Although throughout this course we try to explain difficult concepts in terms we hope all students can understand, sometimes you just need to read or hear about these concepts several times before they sink in. Othertimes, it's not until somebody else explains it in a slightly different way that it finally finds a home in your brain.  To that end, we recommend looking over some other help tutorials and reading. You certainly don't have to go looking at these materials - but if you feel like hearing a different voice, then these are some that I recommend.

Albert Kim stuff?

Andrew Field's statistics in R book - probably the next level up from introduction in terms of R.

Khan Academy videos.(not on R though)

